"""Chapter10d

Revision ID: b92eb3c6107d
Revises: cd5c2ded16fe
Create Date: 2016-08-15 21:49:37.824624

"""

# revision identifiers, used by Alembic.
revision = 'b92eb3c6107d'
down_revision = 'cd5c2ded16fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
